title: David Ohm, PhD
markdown: kramdown

theme: jekyll-theme-minimal



# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Blog
    url: /blog
  - title: Projects
    url: /projects
  - title: Papers
    url: /papers
  # - title: Talks
  #   url: /talks

collections:
  papers:
    output: false # do not create html files for each paper in _papers

defaults:
  - scope:
      type: papers
    values:
      layout: paper

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

permalink:   /:title/

#exclude: ["vender/bundle","lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item # any user-specific listing goes at the end

maruku:
  use_tex:  true

# for clean vector diagrams
assets:
  assets:
    - "*.svg"
  sources:
    - _svg

# http://www.rubydoc.info/gems/jekyll-minify-html/1.1.0
#env: production

#sass:
#  sass_dir: assets/sass
#  style: compressed


responsive_image:
  cache: true
  template: _includes/responsive-image.html
  output_path_format: images/resized/%{width}/%{basename}
  strip: true
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90


